name: basic workflow
on: push
jobs: 
  job01:
      runs-on: ubuntu-latest
      steps:
        - name: step01
          run: echo "Hello World"
          
        - name: install terraform
          uses: hashicorp/setup-terraform@v1

        - name: Terraform init
          run: terraform init
